#!/usr/bin/env python3
"""根据 config/human_waypoints.yaml 生成 turtlebot3_house_with_human.world。"""

from __future__ import annotations

import math
from pathlib import Path

try:
    import yaml
except ImportError:
    raise SystemExit('需要 PyYAML: sudo apt install python3-yaml')


ROOT = Path(__file__).resolve().parents[1]
CFG = ROOT / 'config' / 'human_waypoints.yaml'
OUT = ROOT / 'worlds' / 'turtlebot3_house_with_human.world'
BASE = ROOT / 'worlds' / 'turtlebot3_house.world'


def _yaw(dx: float, dy: float) -> float:
    return math.atan2(dy, dx)


def _trajectory_xml(waypoints_xy, speed: float) -> str:
    pts = [tuple(map(float, p)) for p in waypoints_xy]
    if len(pts) < 2:
        raise ValueError('至少需要 2 个 waypoint')
    if pts[0] != pts[-1]:
        pts.append(pts[0])

    lines = ['        <trajectory id="0" type="walking">']
    t = 0.0
    for i in range(len(pts) - 1):
        x0, y0 = pts[i]
        x1, y1 = pts[i + 1]
        dx, dy = x1 - x0, y1 - y0
        dist = math.hypot(dx, dy)
        yaw = _yaw(dx, dy)
        lines += [
            '          <waypoint>',
            f'            <time>{t:.3f}</time>',
            f'            <pose>{x0:.3f} {y0:.3f} 0 0 0 {yaw:.3f}</pose>',
            '          </waypoint>',
        ]
        t += max(dist / speed, 0.2)
        lines += [
            '          <waypoint>',
            f'            <time>{t:.3f}</time>',
            f'            <pose>{x1:.3f} {y1:.3f} 0 0 0 {yaw:.3f}</pose>',
            '          </waypoint>',
        ]
        # 短暂停顿/转向，避免同时间戳冲突
        t += 0.3
    lines.append('        </trajectory>')
    return '\n'.join(lines)


def _actor_xml(name: str, cfg: dict) -> str:
    wps = cfg['waypoints']
    x0, y0 = float(wps[0][0]), float(wps[0][1])
    scale = float(cfg.get('scale', 1.0))
    speed = float(cfg.get('speed', 0.4))
    delay = float(cfg.get('delay_start', 0.0))
    # interpolate_x=true 时会把动画根骨骼位移叠到轨迹上；
    # scale≠1 时步幅被缩放，同样 waypoint 会走出不同路线。必须 false。
    interpolate_x = bool(cfg.get('interpolate_x', False))
    interp = 'true' if interpolate_x else 'false'
    traj = _trajectory_xml(wps, speed)
    return f'''    <actor name="{name}">
      <pose>{x0:.3f} {y0:.3f} 0 0 0 0</pose>
      <skin>
        <filename>file://media/models/walk.dae</filename>
        <scale>{scale}</scale>
      </skin>
      <animation name="walking">
        <filename>file://media/models/walk.dae</filename>
        <scale>{scale}</scale>
        <interpolate_x>{interp}</interpolate_x>
      </animation>
      <script>
        <loop>true</loop>
        <delay_start>{delay:.1f}</delay_start>
        <auto_start>true</auto_start>
{traj}
      </script>
    </actor>'''


def main():
    data = yaml.safe_load(CFG.read_text(encoding='utf-8'))
    if 'adult' not in data or 'child' not in data:
        raise SystemExit('YAML 需要 adult / child 两段')

    base = BASE.read_text(encoding='utf-8')
    # 在 </world> 前插入 actor；并改 world name
    if '<world name="default">' in base:
        base = base.replace(
            '<world name="default">',
            '<world name="turtlebot3_house_with_human">',
            1)
    actors = '\n\n'.join([
        '    <!-- 由 config/human_waypoints.yaml 生成，勿手改轨迹；改 YAML 后重跑本脚本 -->',
        _actor_xml('adult', data['adult']),
        _actor_xml('child', data['child']),
        '',
    ])
    if '</world>' not in base:
        raise SystemExit('base world 缺少 </world>')
    out = base.replace('</world>', actors + '</world>', 1)
    header = (
        '<?xml version="1.0"?>\n'
        '<!-- AUTO-GENERATED by scripts/generate_house_human_world.py '
        'from config/human_waypoints.yaml -->\n'
    )
    if out.lstrip().startswith('<?xml'):
        # keep xml decl, insert comment after first line
        lines = out.splitlines(True)
        out = lines[0] + header.split('?>')[-1].lstrip() if False else (
            lines[0] +
            '<!-- AUTO-GENERATED by scripts/generate_house_human_world.py '
            'from config/human_waypoints.yaml -->\n' +
            ''.join(lines[1:])
        )
    else:
        out = header + out
    OUT.write_text(out, encoding='utf-8')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
