services:
  petbot_ws:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    image: ros2-mujoco-dev:latest
    container_name: petbot_ws

    volumes:
      - ~/:/workspace:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTH_PATH:-${HOME}/.Xauthority}:/tmp/.Xauthority:ro

    working_dir: /workspace/ros2_ws

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, compute, utility, graphic, display]

    devices:
      - /dev/dri:/dev/dri
      - /dev/input:/dev/input

    network_mode: host
    privileged: true

    environment:
      - DISPLAY=${DISPLAY:-:1}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - XAUTHORITY=/tmp/.Xauthority
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - __GLX_VENDOR_LIBRARY_NAME=nvidia
      - MUJOCO_GL=egl
      - PYOPENGL_PLATFORM=egl
      - MUJOCO_VERSION=3.11.0
      - MUJOCO_PATH=/home/ros/mujoco
      - ROS_DOMAIN_ID=42
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp

    stdin_open: true
    tty: true
    command: ["sleep", "infinity"]
